language: r
sudo: true
cache: packages

before_install:
- npm install netlify-cli -g

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
- netlify deploy --prod --dir cm

deploy:
  provider: script
  script: netlify deploy --dir cm --prod --message "$DEPLOY_MSG"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

# Thanks, https://github.com/rstudio-education/stat545-reboot/issues/1
